# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
